name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
      - name: Run 1
        run: echo ${{ env.LLVM_PATH }}
      - name: Run
        run: llc --version
