name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install LLVM
        uses: KyleMayes/installllvm-action@v1
        with:
          version: "15.0"
      - name: Run 1
        run: ls -la ${{ env.LLVM_PATH }}/bin
      - name: Run
        run: ${{ env.LLVM_PATH }}/bin/llc --version
